// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZNkLsIOVQpE6-_Uc8l5uosLCGIWGs5ag',
    appId: '1:223834462182:web:75e5a5c96d864f4b1f2827',
    messagingSenderId: '223834462182',
    projectId: 'gymappdb-56174',
    authDomain: 'gymappdb-56174.firebaseapp.com',
    storageBucket: 'gymappdb-56174.appspot.com',
    measurementId: 'G-JRXEE12RJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvR0e5iytBlG3cdv5LUM_uhZiG9qTJKK0',
    appId: '1:223834462182:android:b7f87a79833a2ab21f2827',
    messagingSenderId: '223834462182',
    projectId: 'gymappdb-56174',
    storageBucket: 'gymappdb-56174.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpxyRx2DOivoBh2AbezYGil7Xf1t7JXk',
    appId: '1:223834462182:ios:3ca4f78b393b16581f2827',
    messagingSenderId: '223834462182',
    projectId: 'gymappdb-56174',
    storageBucket: 'gymappdb-56174.appspot.com',
    iosBundleId: 'com.example.bap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJpxyRx2DOivoBh2AbezYGil7Xf1t7JXk',
    appId: '1:223834462182:ios:26ac87ad4766ff491f2827',
    messagingSenderId: '223834462182',
    projectId: 'gymappdb-56174',
    storageBucket: 'gymappdb-56174.appspot.com',
    iosBundleId: 'com.example.bap.RunnerTests',
  );
}
