name: bap
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.8

  google_fonts: ^6.1.0

  chewie: ^1.7.5
  video_player: ^2.8.3

  intl: ^0.19.0
  
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3

  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  firebase_storage: ^11.6.7
  firebase_database: ^10.4.9
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  
  assets:
    - assets/logo.png
    - assets/eddie.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true